---

**Load essential libraries**

---

In [2]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('dark_background')
%matplotlib inline
import tensorflow as tf

In [ ]:
A = np.random.randint(-5, 6, 15).reshape(5, 3)
#print(A)
v = np.array([1, 2, 3])
#print(v)
#print(np.dot(A, v))
T = np.random.randint(-5, 6, 45).reshape(3, 5, 3)
print(T)
print(v)
print(np.dot(T, v))
print(np.dot(T[0], v))

In [22]:
I = np.identity(3)
print(I)
A = tf.nn.softmax(tf.constant(np.reshape(np.random.randint(-3, 3, 12), (4, 3)), dtype = tf.float32), axis = 1).numpy()
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.01766842 0.9646631  0.01766842]
 [0.93623954 0.04661262 0.01714783]
 [0.11731042 0.8668133  0.01587624]
 [0.25949645 0.03511902 0.7053845 ]]


In [23]:
A.shape

(4, 3)

In [26]:
A[:, :, np.newaxis].shape

(4, 3, 1)

In [27]:
A[:, :, np.newaxis]

array([[[0.01766842],
        [0.9646631 ],
        [0.01766842]],

       [[0.93623954],
        [0.04661262],
        [0.01714783]],

       [[0.11731042],
        [0.8668133 ],
        [0.01587624]],

       [[0.25949645],
        [0.03511902],
        [0.7053845 ]]], dtype=float32)

In [28]:
I - A[:, :, np.newaxis]

array([[[ 0.98233158, -0.01766842, -0.01766842],
        [-0.96466309,  0.03533691, -0.96466309],
        [-0.01766842, -0.01766842,  0.98233158]],

       [[ 0.06376046, -0.93623954, -0.93623954],
        [-0.04661262,  0.95338738, -0.04661262],
        [-0.01714783, -0.01714783,  0.98285217]],

       [[ 0.88268958, -0.11731042, -0.11731042],
        [-0.8668133 ,  0.1331867 , -0.8668133 ],
        [-0.01587624, -0.01587624,  0.98412376]],

       [[ 0.74050355, -0.25949645, -0.25949645],
        [-0.03511902,  0.96488098, -0.03511902],
        [-0.70538449, -0.70538449,  0.29461551]]])

In [29]:
A[:, np.newaxis, :].shape

(4, 1, 3)

In [30]:
A[:, np.newaxis, :]

array([[[0.01766842, 0.9646631 , 0.01766842]],

       [[0.93623954, 0.04661262, 0.01714783]],

       [[0.11731042, 0.8668133 , 0.01587624]],

       [[0.25949645, 0.03511902, 0.7053845 ]]], dtype=float32)

In [32]:
local_gradient = (I - A[:, :, np.newaxis]) * A[:, np.newaxis, :]
print(local_gradient)

[[[ 0.01735625 -0.01704407 -0.00031217]
  [-0.01704407  0.03408821 -0.01704407]
  [-0.00031217 -0.01704407  0.01735625]]

 [[ 0.05969506 -0.04364058 -0.01605447]
  [-0.04364058  0.04443989 -0.00079931]
  [-0.01605447 -0.00079931  0.01685378]]

 [[ 0.10354869 -0.10168623 -0.00186245]
  [-0.10168623  0.115448   -0.01376174]
  [-0.00186245 -0.01376174  0.01562418]]

 [[ 0.19215804 -0.00911326 -0.18304477]
  [-0.00911326  0.03388568 -0.02477241]
  [-0.18304477 -0.02477241  0.20781721]]]


In [33]:
output_gradient = np.random.rand(4, 3)
print(output_gradient)

[[0.55776608 0.1286046  0.6198569 ]
 [0.48339594 0.36152103 0.23079323]
 [0.66710633 0.27260656 0.21904366]
 [0.74528399 0.47114234 0.81811243]]


In [34]:
np.einsum('ij, ijk -> ik', output_gradient, local_gradient)

array([[ 0.00729528, -0.01568759,  0.00839232],
       [ 0.0093741 , -0.0052142 , -0.00415989],
       [ 0.04094969, -0.03937807, -0.00157161],
       [-0.01083253, -0.01109361,  0.02192617]])

In [38]:
np.dot(output_gradient[0].reshape(1, -1), local_gradient[0])

array([[ 0.0093741 , -0.0052142 , -0.00415989]])

In [45]:
X = np.reshape(np.random.randint(-5, 6, 20), (4, 5))
print(X)
G = np.random.rand(4, 3)
print(G)
np.einsum('ij, ik -> jk', X, G)

[[-4 -2  0 -3 -5]
 [ 4 -1 -4 -4 -4]
 [ 2  2 -5  5 -4]
 [ 3  4  3 -3 -1]]
[[0.7007317  0.12466013 0.27793579]
 [0.50338183 0.65104423 0.10318189]
 [0.87104557 0.81774509 0.10731554]
 [0.79953312 0.71471532 0.96481531]]


array([[ 3.35129099,  5.88517254,  2.41006143],
       [ 3.03537838,  3.59398697,  3.41483885],
       [-3.97015579, -4.54875642,  1.94514069],
       [-2.15909395, -1.03357785, -3.6044032 ],
       [-9.80090122, -7.21317329, -3.19648397]])

In [47]:
np.dot(X[0].reshape(-1, 1), G[0].reshape(1, -1)) +\
 np.dot(X[1].reshape(-1, 1), G[1].reshape(1, -1)) +\
  np.dot(X[2].reshape(-1, 1), G[2].reshape(1, -1)) +\
   np.dot(X[3].reshape(-1, 1), G[3].reshape(1, -1))

array([[ 3.35129099,  5.88517254,  2.41006143],
       [ 3.03537838,  3.59398697,  3.41483885],
       [-3.97015579, -4.54875642,  1.94514069],
       [-2.15909395, -1.03357785, -3.6044032 ],
       [-9.80090122, -7.21317329, -3.19648397]])